[package]
name = "spotify-but-with-shuffle-fixed"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.40", features = ["full"] }
tracing = "0.1"
tracing-subscriber = "0.3"
rspotify = { version = "0.13", features = ["cli"] }
futures = "0.3"
rand = "0.9.0-alpha.2"
